#!/usr/bin/env python3
"""Generate uwidth's width tables from the Unicode Character Database.

Reads four UCD data files (all one Unicode release) and emits `src/tables.rs`:
two sorted, merged, disjoint range tables plus the source Unicode version.

  width 0 : C0/C1 controls (handled in code, not tabled), combining marks
            (gc = Mn, Me), Default_Ignorable_Code_Point (ZWSP/ZWNJ/ZWJ/...),
            and conjoining Hangul Jamo (medial + final).
  width 2 : East Asian Wide (W) and Fullwidth (F), plus Emoji_Presentation.
  width 1 : everything else (East Asian Ambiguous defaults to 1).

The two tables are made disjoint (zero-width wins) so lookup order is irrelevant.

Usage: python gen_tables.py <ucd_dir> <out_rs>
"""
import re
import sys

RANGE_RE = re.compile(r"^([0-9A-Fa-f]+)(?:\.\.([0-9A-Fa-f]+))?\s*;\s*(\S+)")


def parse(path, wanted):
    """Yield ints whose property field (after ';') is in `wanted`."""
    out = set()
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            m = RANGE_RE.match(line)
            if not m:
                continue
            prop = m.group(3)
            if prop not in wanted:
                continue
            lo = int(m.group(1), 16)
            hi = int(m.group(2), 16) if m.group(2) else lo
            out.update(range(lo, hi + 1))
    return out


def to_ranges(cps):
    """Sorted set of ints -> merged inclusive (lo, hi) ranges."""
    ranges = []
    for cp in sorted(cps):
        if ranges and cp == ranges[-1][1] + 1:
            ranges[-1][1] = cp
        else:
            ranges.append([cp, cp])
    return [(lo, hi) for lo, hi in ranges]


def main():
    ucd, out = sys.argv[1], sys.argv[2]

    zero = parse(f"{ucd}/DerivedGeneralCategory.txt", {"Mn", "Me"})
    zero |= parse(f"{ucd}/DerivedCoreProperties.txt", {"Default_Ignorable_Code_Point"})
    # Conjoining Hangul Jamo medial/final combine onto a leading jamo and take
    # no cell of their own; the leading jamo (U+1100..115F, EAW W) carries the
    # width. gc marks these Lo, so add them explicitly.
    zero |= set(range(0x1160, 0x11FF + 1))  # Hangul Jamo medial + final
    zero |= set(range(0xD7B0, 0xD7C6 + 1))  # Hangul Jamo Extended-B medial
    zero |= set(range(0xD7CB, 0xD7FB + 1))  # Hangul Jamo Extended-B final

    wide = parse(f"{ucd}/EastAsianWidth.txt", {"W", "F"})
    wide |= parse(f"{ucd}/emoji-data.txt", {"Emoji_Presentation"})

    # Zero-width wins: a combining/ignorable codepoint is never wide.
    wide -= zero

    zr = to_ranges(zero)
    wr = to_ranges(wide)

    def emit(name, ranges):
        lines = [f"pub(crate) static {name}: &[(u32, u32)] = &["]
        for lo, hi in ranges:
            lines.append(f"    (0x{lo:04X}, 0x{hi:04X}),")
        lines.append("];")
        return "\n".join(lines)

    with open(out, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(
            "// @generated by tools/gen_tables.rs data pipeline "
            "(tools/gen_tables.py) from the\n"
            "// Unicode 16.0.0 Character Database. Do not edit by hand; "
            "regenerate instead.\n\n"
            "/// The Unicode release these tables were generated from.\n"
            "pub const UNICODE_VERSION: (u8, u8, u8) = (16, 0, 0);\n\n"
            "/// Codepoints that occupy zero display columns (combining marks,\n"
            "/// default-ignorable format chars, conjoining Hangul Jamo).\n"
            f"{emit('ZERO_WIDTH', zr)}\n\n"
            "/// Codepoints that occupy two display columns (East Asian Wide/\n"
            "/// Fullwidth and emoji with default emoji presentation).\n"
            f"{emit('WIDE', wr)}\n"
        )

    print(f"ZERO_WIDTH ranges: {len(zr)}  ({len(zero)} codepoints)")
    print(f"WIDE ranges:       {len(wr)}  ({len(wide)} codepoints)")


if __name__ == "__main__":
    main()
